name: Packer Status Check

on:
  pull_request:
    branches:
      - main  # Runs on PRs to main

jobs:
  packer-status-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Packer
        uses: hashicorp/setup-packer@v2

      - name: Check if Packer Template Exists
        run: |
          if [ ! -f packer/template.pkr.hcl ]; then
            echo "Packer template file not found!"
            exit 1
          fi

      - name: Build WebApp Artifact
        run: |
          mkdir -p packer/files
          zip -r packer/files/webapp.zip . -x "node_modules/*" -x ".git/*"

      - name: Packer Format Check
        id: fmt
        run: packer fmt -check packer/template.pkr.hcl

      - name: Packer Init
        run: packer init packer/

      # Set environment variables for Packer (removed GCP-related variables)
      - name: Set Environment Variables
        run: |
          echo "ami_id=${{ vars.AMI_ID }}" >> $GITHUB_ENV

      # Validate Packer Template
      - name: Packer Validate
        shell: bash
        run: |
          packer validate -var "ami_id=${{vars.AMI_ID}}" packer/template.pkr.hcl
