name: Packer AMI Build

on:
  push:
    branches:
      - main  # Runs the workflow only when pushing to the "main" branch

jobs:
  packer-build:
    runs-on: ubuntu-latest  # Uses the latest Ubuntu runner in GitHub Actions

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Run application tests
      - name: Run tests
        run: npm test

      # Create the webapp artifact (ZIP the project excluding unnecessary files)
      - name: Build Application Artifact
        run: |
          mkdir -p packer/files
          zip -r packer/files/webapp.zip . -x ".git/*" ".github/*" "node_modules/*"

      # AWS Authentication - Configure AWS CLI for Packer 
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Install Packer
      - name: Set up Packer
        uses: hashicorp/setup-packer@v2

      # Set environment variables for Packer
      - name: Set Environment Variables
        run: |
          echo "ami_id=${{ vars.AMI_ID }}" >> $GITHUB_ENV

      # Validate Packer Template
      - name: Packer Validate
        shell: bash
        run: |
          packer init packer/
          packer validate -var "ami_id=${{vars.AMI_ID}}" packer/template.pkr.hcl

      # Build AMI
      - name: Build AMI
        shell: bash
        run: packer build -var "ami_id=${{vars.AMI_ID}}" packer/template.pkr.hcl
