name: Packer Status Check

on:
  pull_request:
    branches:
      - main

jobs:
  packer-status-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Packer
        uses: hashicorp/setup-packer@v2

      # Ensure packer template exists before running checks
      - name: Check if Packer Template Exists
        run: |
          if [ ! -f packer/template.pkr.hcl ]; then
            echo "Packer template file not found!"
            exit 1
          fi

      # Ensure correct formatting
      - name: Packer Format Check
        id: fmt
        run: packer fmt -check packer/template.pkr.hcl

      - name: Check if Packer Format Changed Files
        if: steps.fmt.outcome != 'success'
        run: |
          echo "Packer template is not formatted correctly. Run 'packer fmt' locally."
          exit 1

      # Initialize Packer before validation
      - name: Packer Init
        run: packer init packer/

      # Create Dummy Application Artifact for Validation
      - name: Create Dummy Application Artifact for Validation
        run: |
          mkdir -p packer/files
          echo "This is a dummy webapp artifact for validation." > dummy.txt
          tar -czvf packer/files/webapp.tar.gz dummy.txt

      # Validate the Packer template with required variables from GitHub Secrets/Variables
      - name: Packer Validate
        env:
          POSTGRES_USER: ${{ vars.POSTGRES_USER }}           # GitHub Variable
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }} # GitHub Secret
        run: |
          packer validate \
            -var "POSTGRES_USER=$POSTGRES_USER" \
            -var "POSTGRES_PASSWORD=$POSTGRES_PASSWORD" \
            packer/template.pkr.hcl

